#!/bin/bash
echo "input commit"
read var

git add .
git commit -m "${var}"
git push
~                                                                                                                                                                       
~                                                                                                                                                                       
~                            
